name = "geekcard"
main = "src/worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "geekcard-db"
database_id = "COLOQUE-O-ID-AQUI-APOS-CRIAR-O-D1"

[vars]
RESUMO_HORARIO = "30 17 * * *"

[[triggers]]
crons = ["30 17 * * *", "*/30 * * * *", "0 8 * * *"]
